added init and config
void-tech-um/open-course pull request #2
Opened 2023-10-22 21:43 UTC by alexbnewman

2023-10-22 21:44 UTC, amoghmadireddi commented
Looks good

2023-10-22 22:01 UTC, amoghmadireddi approved these changes
Looks good

2023-10-23 02:41 UTC, jennweir commented on application/config.py
> +UPLOAD_FOLDER = APPLICATION_ROOT/'var'/'uploads'
We'll be using some sort of content delivery network instead of storing files on the user's computer, thus UPLOAD_FOLDER variable is not necessary. Please delete line 11 before we merge.

2023-10-23 02:42 UTC, jennweir requested changes
Delete UPLOAD_FOLDER variable before we merge. Otherwise, looks great! Nice work :)

2023-10-29 21:42 UTC, tinglu12 approved these changes
good

2023-10-29 21:44 UTC, mnkelkar approved these changes
i approve

2023-10-31 20:10 UTC, merged