Profile Page
void-tech-um/open-course pull request #22
Opened 2024-02-04 22:28 UTC by philipchurchley

Copied the changes from "profile" branch to a new branch that has the updated code from main.

2024-02-04 22:29 UTC, reikoc1735 approved these changes

2024-02-04 22:29 UTC, reneerchen approved these changes

2024-02-04 22:29 UTC, Becky2005 approved these changes

2024-02-04 22:55 UTC, jennweir requested changes
Please address the changes before this merge is completed.

2024-02-04 22:55 UTC, jennweir commented on application/templates/profile.html
> +        <link rel="stylesheet" type="text/css" href="/static/css/style.css" />
Try to look at the differences between your file and the previous profile.html page. Consider the fact that the head and body tags are no longer required since they are included in base.html
Pasting in your changes is good but should follow the practice of now only including your div based on the content you wrote.

2024-02-04 22:55 UTC, jennweir commented on application/templates/profile.html
> +        <div id="accountSetting">
Your code starts here on line 21 and ends at line 107. These are the contents that should have been pasted into the profile.html that existed on main

2024-02-04 22:55 UTC, jennweir commented on application/templates/profile.html
> -    <h1>Profile Page</h1>
I also do not want to completely delete this portion yet since it serves as an example for passing context and connecting to the database.

2024-02-08 01:19 UTC, jennweir commented
Addressed issues and pushed to main directly with the changes.

2024-02-08 01:19 UTC, closed without merging