join function added
void-tech-um/open-course pull request #24
Opened 2024-02-15 02:06 UTC by reikoc1735

Implemented get user courses to join.html (so it will create a button for every course the user is enrolled in)

2024-02-15 15:19 UTC, Becky2005 approved these changes

2024-02-15 15:50 UTC, jennweir requested changes
One quick fix that the function decorator (mentioned below) for the join function to be addressed, otherwise this is awesome!

2024-02-15 15:50 UTC, jennweir commented on application/views/join.py
> +    """Display /profile route."""
This comment needs to be updated with "Display /join/ route."

2024-02-17 23:28 UTC, tinglu12 approved these changes

2024-02-18 20:46 UTC, merged